### ISSUE TITLE
CERTIFICATE ISSUE 

### ISSUE THREAD

**Issue by ryantrung0620** [Tim-herbie/k8s_fortigate_exporter#1]
Hi Tim

I'm following your instructions and success to deploy Fortinet exporter in Kubernetes, but I get the problem with certificate because my firewall using self sign certificate, so can you please help me how can I config to ignore certificate check or add my certificate to this deployment , my error code as below : 

Error: Get "https://x.x.x.x/api/v2/monitor/firewall/policy/select?vdom=*&ip_version=ipv4": x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs

Thanks
Ryan

**Comment by Tim-herbie** [comment]
Hi Ryan

thank you for your request! Yes, it should be possible to ignore the certificate issue. For this, you have to replace the deployment file with the following content (which adds the insecure command). 

This could help you:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortigate-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortigate-exporter
  template:
    metadata:
      labels:
        app: fortigate-exporter
    spec:
      containers:
      - name: fortigate-exporter
        image: kifeo/fortigate_exporter
        ports:
        - containerPort: 9710
        volumeMounts:
          - name: fortigate-credentials
            mountPath: /config
        command: ["-insecure"] # Add the -insecure command here
      volumes:
        - name: fortigate-credentials
          secret:
            secretName: fortigate-credentials

```

**Comment by ryantrung0620** [comment]
Hi Tim
Thanks for your reply , i tried as your instruction but i'm not sure what is the correct command to input , below is what i did 
1) keep the same code you provide and i get error 
  _Warning  Failed     8s (x2 over 10s)   kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-insecure": executable file not found in $PATH: unknown_
2) Tried to add the PATH to command : 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortigate-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortigate-exporter
  template:
    metadata:
      labels:
        app: fortigate-exporter
    spec:
      containers:
      - name: fortigate-exporter
        image: kifeo/fortigate_exporter
        ports:
        - containerPort: 9710
        volumeMounts:
          - name: fortigate-credentials
            mountPath: /config
        command: ["/opt/fortigate_exporter/fortigate-exporter", "-insecure"] # add PATH : /opt/fortigate_exporter/fortigate-exporter
      volumes:
        - name: fortigate-credentials
          secret:
            secretName: fortigate-credentials
```

 and still get the error 
  _Warning  Failed     2s (x3 over 23s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/fortigate_exporter/fortigate-exporter": stat /opt/fortigate_exporter/fortigate-exporter: no such file or directory: unknown_

Please help to correct the command

**Comment by Tim-herbie** [comment]
Hi Ryan,

sorry for my late answer. I build the image on my own, added the "-insecure" cli parameter and pushed it to dockerhub.. I changed the image in the following code. Please try this code and share your results with me:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortigate-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortigate-exporter
  template:
    metadata:
      labels:
        app: fortigate-exporter
    spec:
      containers:
      - name: fortigate-exporter
        image: therbert6/fortigate-exporter:0.1-insecure
        ports:
        - containerPort: 9710
        volumeMounts:
          - name: fortigate-credentials
            mountPath: /config
      volumes:
        - name: fortigate-credentials
          secret:
            secretName: fortigate-credentials
```
